PATCH http://localhost:3000/posts/1
Content-Type: application/json

{
  "title": "CRUD automático com NestJS e Prisma",
  "content": "Aprenda a fazer um CRUD automático com NestJS e Prisma.",
  "published": false,
  "authorId": 1
}
